source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem 'wdm', '>= 0.1.0' if Gem.win_platform?

gem 'faraday', '~> 2.7', '>= 2.7.11'
gem "github-pages", group: :jekyll_plugins
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
gem "webrick", "~> 1.8"